services:
  aspnet_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Change to Production as needed
    ports:
      - "5171:8080"  # Change to your preferred port -> host_port:container_port
    volumes:
      - .:/app/src
      - /app/bin
      - /app/obj
    command: dotnet watch run
