services:
  aspnet_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Change to Production as needed
    ports:
      - "5171:80"  # Change to your preferred port
    volumes:
      - .:/app/src